# Generated by Django 4.2.18 on 2026-02-19 23:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('titulo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Instrutor',
            fields=[
                ('id', models.AutoField(help_text='ID do instrutor', primary_key=True, serialize=False)),
                ('rg', models.CharField(help_text='código do RG', max_length=15)),
                ('nome', models.CharField(help_text='Nome do instrutor', max_length=70)),
                ('dataNascimento', models.DateField(help_text='Data de nascimento')),
                ('telefone', models.CharField(help_text='Telefone para contato', max_length=9)),
                ('ddd', models.CharField(help_text='DDD do seu estado', max_length=3)),
                ('codigoTitulo', models.ForeignKey(db_column='codigoTitulo', help_text='Informe o código do titulo do instrutor', on_delete=django.db.models.deletion.PROTECT, to='titulo.titulo')),
            ],
        ),
    ]
