# Generated by Django 4.2.18 on 2026-02-24 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instrutor', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instrutor',
            name='codigoTitulo',
        ),
        migrations.AddField(
            model_name='instrutor',
            name='codigo_titulo',
            field=models.IntegerField(help_text='Título do instrutor', null=True),
        ),
    ]
