# Generated by Django 4.2.18 on 2026-02-10 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tipodeatividade', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipodeatividade',
            name='codigo',
            field=models.AutoField(help_text='código do tipo de atividade', primary_key=True, serialize=False),
        ),
    ]
